### ISSUE TITLE
Why the app needs write permission?

### ISSUE THREAD

**Issue by kinoh** [cordx56/tweet-generator#2]
Only reading API seems to be used.

**Comment by cordx56** [comment]
Thank you for your comment.
I developed this application as a bot application at first. And I still use this API keys in bot application.
Your comment has a point. but I cannot change permission immediatly.
This application never use write permission. I'll change permission settings later.
sorry for making you worry

**Comment by cordx56** [comment]
I created new app in Twitter Developers site, and replaced keys just now.
new app doesn’t need write permission.

**Comment by kinoh** [comment]
Thank you for your immediate action! 👍👍👍
